services:
    app:
      build: .
      container_name: web_app
      ports:
        - "18080:18080"
      environment:
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
      depends_on:
        db:
          condition: service_healthy

    db:
      image: postgres:14-alpine
      container_name: postgres_db
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d $${DB_NAME} -U $${DB_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - ${DB_PORT}:5432
      volumes:
        - ./data/db:/var/lib/postgresql/data
      attach: false
